---


- name: common | Create the directories for site specific configurations
  file: 
      path="{{nginx_etc}}/{{item}}"
      state=directory 
      owner=root 
      group=root 
      mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"

- name: common | Copy the nginx default configuration file 
  template: 
     src=default.conf.j2 
     dest="{{nginx_etc}}/conf.d/default.conf"

- name: common | Copy the nginx default site configuration file 
  template: 
     src=default.j2 
     dest="{{nginx_etc}}/sites-available/default"

- name: common | Create the link for site enabled specific configurations
  file: 
      path="{{nginx_etc}}/sites-enabled/default"
      state=link 
      src="{{nginx_etc}}/sites-available/default"

- name: common | Create the  configuration files for nginx
  template: 
      src=site.j2 
      dest="{{nginx_etc}}/conf.d/{{item.file_name}}.conf"
  with_items: nginx_conf

  when: nginx_conf |lower != 'none'
  notify: 
   - reload nginx

- name: common | Copy the nginx main configuration file 
  template: 
      src=nginx.conf.j2
      dest="{{nginx_etc}}/nginx.conf"
      validate='nginx -t -c %s'
  notify: 
   - restart nginx   

- name: common | start the nginx service
  service: 
      name=nginx 
      state=started 
      enabled=yes