---

- name: nginx_debian | Install the nginx packages 
  apt: 
      name={{ item }} 
      state=present 
      update_cache=yes
  with_items: ubuntu_pkg
  environment: env
  when: ansible_os_family == "Debian"